# Teste de Sistema de Detecção de Fraudes

Teste utilizando o OneClassSVM, que é uma implementação de Support Vector Machine para Unsupervised Learning

Nessa versão o teste é bem simples, utiliza só duas features e não faz tantos testes de configuração da SVM. Quero fazer uma outra versão pra comparar SVM, Logistic Regression e Neural Network. Al[em disso, usar GridSearch para teste de parâmetros etc

In [501]:
from sklearn import svm
import numpy as np
from sklearn import preprocessing



- Features layout: cod.cidade, valor compra
  - cod. cidade = 1 sp, 2 jundiai, 3 campinas, 4 sorocaba, 5 internet
  - local: 1 shoppping, 2 posto gasolina, 3 feira livre, 4 restaurante
  
** Create a list for training using a random number generator **



In [502]:
import random

X = np.ones((50,2))

for i in range(50):
    X [i][0] = random.uniform(1.0,4.0)
    X [i][1] = random.uniform(50.0,200.0)



#print X



** Normalize data for SVM training **

This is a ** very ** important step, specially because the features are in a very different range

** Nota: ** o Objeto standard, criado aqui, será utilizado abaixo, nos testes, para normalizar os dados de testes baseados nos parametros de normalização usados aqui no treinamento

In [503]:
standard = preprocessing.StandardScaler().fit(X)
df_std = standard.transform(X)
X = df_std

print type(df_std)
print df_std.shape

<type 'numpy.ndarray'>
(50, 2)


In [504]:

print type(X)
print X.shape

#print X


clsf = svm.OneClassSVM(nu=0.1,kernel='rbf',gamma=0.1)

clsf.fit(X)

#print "decision function"
#clsf.decision_function(X)



<type 'numpy.ndarray'>
(50, 2)


OneClassSVM(cache_size=200, coef0=0.0, degree=3, gamma=0.1, kernel='rbf',
      max_iter=-1, nu=0.1, random_state=None, shrinking=True, tol=0.001,
      verbose=False)

## Create fake data to test values in which we want to detect as normal entries (not fraud)


In [505]:

count = 0
for i in range (50):
    p1 = random.uniform(1.0,4.0)
    p2 = random.uniform(80.0,180.0)
    v = np.ones((1,2))
    v[0][0] = p1
    v[0][1] = p2
    v = v.reshape(1,-1)
    ori = v
    #print v
    
    # reuse the same standard scaler from the training set.
    df_std = standard.transform(v)
    v = df_std
    #print v
    
    if clsf.predict (v)[0] == 1.:
        count = count + 1
    else:
        print "possivel fraude ?"
        print ori
        
print "Possivelmente dentro da faixa correta: "        
print count


possivel fraude ?
[[   1.0418009   101.95077594]]
possivel fraude ?
[[   1.01461507  170.89541811]]
possivel fraude ?
[[   1.09892722  131.50047767]]
possivel fraude ?
[[  1.0225354   95.25931847]]
Possivelmente dentro da faixa correta: 
46


## Create fake data to test values in which we want to detect as Fraud

Actually, part of it, should as be detected as normal entries, as I put the values or price, starting at 10.0

In [506]:
count = 0
for i in range (50):
    p1 = random.uniform(1.0,8.0)
    p2 = random.uniform(10.0,480.0)
    v = np.ones((1,2))
    v[0][0] = p1
    v[0][1] = p2
    v = v.reshape(1,-1)
    
    # reuse the same standard scaler from the training set.
    df_std = standard.transform(v)
    v = df_std
    #print v
    
    if clsf.predict (v)[0] == -1.:
        count = count + 1
        
print "Possivelmente dentro da faixa de fraude: "        
print count

Possivelmente dentro da faixa de fraude: 
47


In [507]:
import matplotlib.pyplot as plt

%matplotlib inline

#plt.plot(X[:,0],X[:,1],'rp')

Z = clsf.decision_function(X)
#print X[:,1] - Z
                           
Z = Z.reshape(X[:,1].shape)
F = X[:,1] - Z
F2 = X[:,0] - Z

print F.shape    
print Z.shape
print X[:,1].shape
F2 = F2.reshape(X[:,0].shape)

#plt.contour(X[:,0],X[:,1],X[:,1] - Z)

#plt.scatter(X[:,0],X[:,1])
#plt.scatter(X[:,0],F,color='r',marker='+',linewidths=1)
#plt.contour(X,F2,levels=[0])







(50,)
(50,)
(50,)
