# Teste de Sistema de Detecção de Fraudes

Teste utilizando o OneClassSVM, que é uma implementação de Support Vector Machine para Unsupervised Learning

Nessa versão o teste é bem simples, utiliza só duas features e não faz tantos testes de configuração da SVM. Quero fazer uma outra versão pra comparar SVM, Logistic Regression e Neural Network. Al[em disso, usar GridSearch para teste de parâmetros etc

In [15]:
from sklearn import svm
import numpy as np
from sklearn import preprocessing




- Features layout: cod.cidade, valor compra
  - cod. cidade = 1 sp, 2 jundiai, 3 campinas, 4 sorocaba, 5 internet
  - local: 1 shoppping, 2 posto gasolina, 3 feira livre, 4 restaurante
  
** Create a list for training using a random number generator **



In [16]:
import random

X = np.ones((50,2))

for i in range(50):
    X [i][0] = random.randint(1,4)
    X [i][1] = random.uniform(50.0,200.0)



#print X



** Normalize data for SVM training **

This is a ** very ** important step, specially because the features are in a very different range

** Nota: ** o Objeto standard, criado aqui, será utilizado abaixo, nos testes, para normalizar os dados de testes baseados nos parametros de normalização usados aqui no treinamento

In [17]:
standard = preprocessing.StandardScaler().fit(X)
df_std = standard.transform(X)
X = df_std

print type(df_std)
print df_std.shape

<type 'numpy.ndarray'>
(50, 2)


In [18]:

print type(X)
print X.shape

print X


clsf = svm.OneClassSVM(nu=0.1,kernel='rbf',gamma=0.1)

clsf.fit(X)

#print "decision function"
#clsf.decision_function(X)



<type 'numpy.ndarray'>
(50, 2)
[[-1.32067636  0.35590529]
 [-1.32067636  1.93958381]
 [-1.32067636  0.14219066]
 [ 1.32067636 -0.82715451]
 [-1.32067636  0.79317079]
 [-1.32067636 -0.84752768]
 [ 1.32067636 -1.45408459]
 [ 0.44022545 -0.4660429 ]
 [-1.32067636 -0.66192316]
 [-0.44022545  0.02007673]
 [-1.32067636  0.93275399]
 [ 0.44022545 -0.7698409 ]
 [-0.44022545  0.20825408]
 [ 1.32067636 -1.6558988 ]
 [ 0.44022545  1.22317445]
 [ 0.44022545 -1.4039426 ]
 [-0.44022545 -0.77549852]
 [ 0.44022545  0.67053469]
 [ 1.32067636  2.09964844]
 [-0.44022545  0.26685033]
 [-1.32067636 -0.81695165]
 [ 1.32067636  1.8775552 ]
 [ 0.44022545 -0.49608866]
 [ 0.44022545 -1.39083851]
 [ 0.44022545 -0.94636254]
 [ 0.44022545 -0.79062028]
 [ 0.44022545  1.54781522]
 [-0.44022545  0.49158328]
 [-0.44022545  1.48826302]
 [ 0.44022545  0.11572328]
 [-1.32067636  0.22189817]
 [-1.32067636  0.47704623]
 [ 0.44022545  0.09947795]
 [-1.32067636  1.78998367]
 [ 1.32067636 -0.25417674]
 [ 1.32067636 -0.8154616

OneClassSVM(cache_size=200, coef0=0.0, degree=3, gamma=0.1, kernel='rbf',
      max_iter=-1, nu=0.1, random_state=None, shrinking=True, tol=0.001,
      verbose=False)

## Create fake data to test values in which we want to detect as normal entries (not fraud)


In [19]:

count = 0
for i in range (50):
    p1 = random.randint(1,4)
    p2 = random.uniform(80.0,180.0)
    v = np.ones((1,2))
    v[0][0] = p1
    v[0][1] = p2
    v = v.reshape(1,-1)
    ori = v
    #print v
    
    # reuse the same standard scaler from the training set.
    df_std = standard.transform(v)
    v = df_std
    #print v
    
    if clsf.predict (v)[0] == 1.:
        count = count + 1
    else:
        print "possivel fraude ?"
        print ori
        
print "Possivelmente dentro da faixa correta: "        
print count


possivel fraude ?
[[  1.          83.37285077]]
possivel fraude ?
[[  1.         80.1019022]]
possivel fraude ?
[[  1.          82.99516531]]
Possivelmente dentro da faixa correta: 
47


## Create fake data to test values in which we want to detect as Fraud

Actually, part of it, should as be detected as normal entries, as I put the values or price, starting at 10.0


In [24]:
count = 0
for i in range (50):
    p1 = random.randint(1,8)
    p2 = random.uniform(10.0,480.0)
    v = np.ones((1,2))
    v[0][0] = p1
    v[0][1] = p2
    v = v.reshape(1,-1)
    ori = v
    # reuse the same standard scaler from the training set.
    df_std = standard.transform(v)
    v = df_std
    #print v
    
    if clsf.predict (v)[0] == -1.:
        print ori
        count = count + 1
        
print "Possivelmente dentro da faixa de fraude: "        
print count

[[   6.          217.45285909]]
[[   5.          110.31726588]]
[[   7.         335.1583227]]
[[   3.          261.92633366]]
[[   5.          147.03437317]]
[[   1.          333.57135642]]
[[   5.          458.59730418]]
[[   6.          192.74798659]]
[[   1.         290.0351126]]
[[  8.          64.04866038]]
[[   8.          446.45624661]]
[[   8.          301.95484215]]
[[   6.          342.24731587]]
[[   5.          233.99732097]]
[[   7.          458.09589789]]
[[   7.          159.85352813]]
[[   5.          134.83715733]]
[[  7.          89.17908957]]
[[   8.          323.18498789]]
[[   2.          327.12857782]]
[[   7.          280.51939526]]
[[   3.          303.82949335]]
[[   3.         475.1970891]]
[[   1.         223.5667004]]
[[   4.         232.4886499]]
[[   5.          446.61442737]]
[[   6.          391.40251912]]
[[   7.          366.84293969]]
[[   3.          264.16449645]]
[[   3.        354.591501]]
[[   6.          283.28009787]]
[[   4.          342.17077

In [ ]:
import matplotlib.pyplot as plt

%matplotlib inline

#plt.plot(X[:,0],X[:,1],'rp')

Z = clsf.decision_function(X)
#print X[:,1] - Z
                           
Z = Z.reshape(X[:,1].shape)
F = X[:,1] - Z
F2 = X[:,0] - Z

print F.shape    
print Z.shape
print X[:,1].shape
F2 = F2.reshape(X[:,0].shape)

#plt.contour(X[:,0],X[:,1],X[:,1] - Z)

#plt.scatter(X[:,0],X[:,1])
#plt.scatter(X[:,0],F,color='r',marker='+',linewidths=1)
#plt.contour(X,F2,levels=[0])





